export const technologies = [
  {
    name: 'Stripe',
    shortDescription: 'Payment processing and subscription management',
    proficiency: 2,
    description: 'description',
    link: 'https://stripe.com/',
    imgLink: '/tech/stripe.png',
  },
  {
    name: 'Heroku',
    shortDescription: 'Cloud-based application hosting provider',
    proficiency: 2,
    description: 'description',
    link: 'https://www.heroku.com/',
    imgLink: '/tech/heroku.png',
  },
  {
    name: 'Mapbox',
    shortDescription: 'Mapping API (alternative to Google Maps)',
    proficiency: 1,
    description: 'description',
    link: 'https://www.mapbox.com/',
    imgLink: '/tech/mapbox.png',
  },
  {
    name: 'AWS S3',
    shortDescription: 'Cloud-based object storage and versioning',
    proficiency: 1,
    description: 'description',
    link: 'https://aws.amazon.com/s3/',
    imgLink: '/tech/aws-s3.png',
  },
  {
    name: 'Google Analytics',
    shortDescription: 'Free analytics tool for websites',
    proficiency: 1,
    description: 'description',
    link: 'https://analytics.google.com/',
    imgLink: '/tech/google-analytics.png',
  },
  {
    name: 'Unbounce',
    shortDescription: 'A/B testing platform for landing pages',
    proficiency: 1,
    description: 'description',
    link: 'https://unbounce.com/',
    imgLink: '/tech/unbounce.png',
  },
  {
    name: 'Rollbar',
    shortDescription: 'Error monitoring, tracking and resolution platform',
    proficiency: 2,
    description: 'description',
    link: 'https://rollbar.com/',
    imgLink: '/tech/rollbar.png',
  },
  {
    name: 'Sendgrid',
    shortDescription:
      'Communication platform specializing in sending transactional Email',
    proficiency: 1,
    description: 'description',
    link: 'https://sendgrid.com/',
    imgLink: '/tech/sendgrid.png',
  },
  {
    name: 'Twilio',
    shortDescription: 'Platform for phone and text communications',
    proficiency: 1,
    description: 'description',
    link: 'https://www.twilio.com/',
    imgLink: '/tech/twilio.png',
  },
  {
    name: 'Salesforce',
    shortDescription: 'Industry standard CRM platform',
    proficiency: 1,
    description: 'description',
    link: 'https://www.salesforce.com/',
    imgLink: '/tech/salesforce.png',
  },
]

export default technologies
